char LED_STATUS = 1;
char IS_START = 0;
int VOLTAGE = 0;
const int U_BAT_MIN = 160;
int CCPR_CALC = 0;
char DECELERER = 0;
char TEXTE_UART[] = "ETAT: $$, VBAT: $$$, CCPR: $$$$$$\0";
int DISTANCE_OBJET = 0;
int POS_UART = 0;